### ISSUE TITLE
Should we create issues here or use the feature request board?

### ISSUE THREAD

**Issue by jskrzypek** [integromat/vscode-apps-sdk#12]
You have a feature request board on your site (https://www.integromat.com/en/requests/feature-requests/), but that seems more related to the features of the integromat website itself. 

Should we also use that board or feature requests & issues regarding the SDK, or can we create issues here on this repo?

**Comment by patriksimek** [comment]
Hi @jskrzypek, we'd prefer to use this repository for bugs only. Our feature request board helps us prioritize future development. Thank you!
