### ISSUE TITLE
Error when importing app

### ISSUE THREAD

**Issue by willemwollebrants** [integromat/vscode-apps-sdk#21]
Importing an app gives an error: Cannot read property 'getDataAsync' of undefined

Integromat SDK version: 1.1.0
VSCode version: 1.39.2 (on mac)

Version: 1.39.2
Commit: 6ab598523be7a800d7f3eb4d92d7ab9a66069390
Date: 2019-10-15T15:33:00.827Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Darwin x64 18.7.0

**Comment by ma-zal** [comment]
Release 1.3.24 solves it.
