### ISSUE TITLE
"Access Denied" when trying to create a Function

### ISSUE THREAD

**Issue by JosXa** [integromat/vscode-apps-sdk#23]
In VSCode, when executing the `apps-sdk.function.new` command (right click "Function" -> "new Function"), I get an "Access Denied" error no matter which of my apps I try it on:

![image](https://user-images.githubusercontent.com/7313176/71490863-ae945580-2846-11ea-9188-f8dccda8ece2.png)

The extension host trace logs show only the call, but no further information:
`[2019-12-27 01:16:06.177] [exthost] [trace] ExtHostCommands#$executeContributedCommand apps-sdk.function.new`

This is a real blocker to write tests for the app as indicated in the documentation right now.

**System specs:** 
Windows 10
integromat.apps-sdk version 1.1.2
VSCode version 1.40.2

Edit:
Aha, looks like the "+ Create a new IML function" feature is generally unavailable:
![image](https://user-images.githubusercontent.com/7313176/71492353-fec3e580-284f-11ea-9933-734b29e8a726.png)

**Comment by jskrzypek** [comment]
It's been a few months since I worked with integromat, but as far as I can
recall functions were a special feature that you needed to request via
email from the integromat Dev team.

**Comment by JosXa** [comment]
Ah I see, that makes sense. Thanks
