### ISSUE TITLE
"certificate has expired" error when trying to add environment in VS Code

### ISSUE THREAD

**Issue by samsawyer** [integromat/vscode-apps-sdk#37]
I'm trying to follow the [instructions here](https://docs.integromat.com/apps/apps-sdk) to add an environment to connect the extension to my Integromat account, and I keep getting a "certificate has expired" error after entering my API token.

An API call with the same token as below is successful, however:
```
curl --location --request GET 'https://api.integromat.com/v1/whoami' \
    --header 'Authorization: Token {{apiToken}}' \
    --header 'x-imt-apps-sdk-version: 1' 
```

Happy to provide any other information that might be helpful to debug this.

**Comment by ma-zal** [comment]
Outdated issue. Tested and the certificate is valid now.

```
Certification details:
Issued On	Monday, 21 November 2022 at 01:00:00
Expires On	Wednesday, 22 November 2023 at 00:59:59
```
