### ISSUE TITLE
Automatically added library when using debug is not allowed

### ISSUE THREAD

**Issue by derkzomer** [integromat/vscode-apps-sdk#41]
When adding `debug()` to a function the SDK automatically appends `const { debug } = require("console");` to the top of the file. When attempting to save the function is gives an `undefined: Invalid function code.` error. When removing the library reference the code saves correctly.

![image](https://user-images.githubusercontent.com/5495981/130542433-778e6db6-6a13-4c72-a739-f31862146a97.png)

![image](https://user-images.githubusercontent.com/5495981/130542454-c41f5594-4329-439a-aafb-4d717569a021.png)

**Comment by ma-zal** [comment]
Sorry, but it is not able to `require` any external library.

For debugging it can be useful the `Integromat DevTool` browser extension:
https://docs.integromat.com/apps/integromat-devtool
