### ISSUE TITLE
Refreshing does not work

### ISSUE THREAD

**Issue by Gobliins** [integromat/vscode-apps-sdk#42]
Hello,

i have imported my app from integromat and all code appeared in VSCode.
When i do changes via web interface and click on refresh inside VSCode, nothing is updated.

**Comment by fmalgero** [comment]
Same here......any update?

**Comment by ma-zal** [comment]
If you are talking about already opened file in VS code, it is not refreshed from API after opening. But if you close it and open again, then the fresh version is loaded from Make server on each open.
