### ISSUE TITLE
Cannot create new app

### ISSUE THREAD

**Issue by RedLady** [integromat/vscode-apps-sdk#44]
Issue Type: <b>Bug</b>

When I try to create a new app I am able to enter the name, version, description and color... But when it asks for the language, I type in "English" and the prompter just disappears. If I type in nothing, the prompter disappears. No matter what I do, I cannot get past this step. No app is created. I am not given the dropdown option to choose a language and I cannot move onto the country/global step in the app creation process.

Extension version: 1.3.9
VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:40:02.816Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz (8 x 2995)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.71GB (3.15GB free)|
|Process Argv|--crash-reporter-id 63e17050-ed50-490d-b0be-307dce5a7225|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392cf:30425750
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30424896
pythonvs932:30410667
vscop804cf:30404767
vscop940:30404999
vsrem710:30416614
vsbas813:30426126
vsic-wlc-tsjs:30426436

```

</details>

**Comment by emargareten** [comment]
same here

**Comment by jozinovo** [comment]
I can see that you are using the old version. It works fine for me in version 1.3.10

![image](https://user-images.githubusercontent.com/68340744/163117034-a5c602a8-22d8-45dd-ac3a-75eb145efd25.png)

![image](https://user-images.githubusercontent.com/68340744/163117045-54bf32ae-87fd-45c3-a3c9-ea486fff8b70.png)

**Comment by gocar-hunghoang** [comment]
I also faced the same issue with extension version 1.3.10

**Comment by gocar-hunghoang** [comment]
I found the root cause after some research.
I am running VS Code from Downloads folder(MacOS), it worked well after moved to other folder.
