### ISSUE TITLE
New Make scenario variables ("id", "url", "name", etc) are not supported by the vsc extension

### ISSUE THREAD

**Issue by dinalivia** [integromat/vscode-apps-sdk#49]
I'd like to update some Make modules, adding the scenario URL to an API call but unfortunately, I could not find how to do so.
My current module uses the already existing "executionId" variable, which works fine but I'm unable to use the new ones provided by [this release](https://www.make.com/en/help/about-make/release-notes#july-27--2022).

<img width="324" alt="Screenshot 2022-09-05 at 17 13 42" src="https://user-images.githubusercontent.com/12168858/188479509-a16f9cb3-6728-43e9-889c-b48de3cf2aa5.png">

PS: I've tried using {{url}}, {{var.scenario.url}} and {{scenario.url}} but none was successful. I'd appreciate if the new system variables could be used in the modules too.

**Comment by losahlmann-make** [comment]
Hi,
the context of the custom/system variables is different to the context of the custom apps. So it's currently not possible to access the variable value directly via IML syntax. However, you can define an input field in your module that takes the variable as input in the module UI.
