### ISSUE TITLE
Extension not found in Marketplace?

### ISSUE THREAD

**Issue by NicoHood** [integromat/vscode-apps-sdk#55]
Hi,
I tried to install the app from the marketplace, but it seems it cannot be found. I feel like being super stupid, but can you help?

![image](https://user-images.githubusercontent.com/6888294/200126409-86f43458-f887-4ce6-aa42-e5bdbe28e561.png)

The [visual studio website](https://marketplace.visualstudio.com/items?itemName=Integromat.apps-sdk) says I need to run this command, but that opens the section in the screenshot above.
![image](https://user-images.githubusercontent.com/6888294/200126435-778407d6-94f1-4255-911c-cd8ed72376c6.png)

Any ideas?

**Comment by NicoHood** [comment]
Alright, so the reason for this seems to be that on archlinux only the OpenVSX Store seems to be supported.
https://github.com/microsoft/vscode/issues/107997#issuecomment-703245178

So I would ask make to also publish the package there as well: https://www.eclipse.org/community/eclipse_newsletter/2020/march/1.php

**Comment by ma-zal** [comment]
Hi @NicoHood. Thank you for introducting the Eclipse Theia and the Eclipse Open VSX.
Unfortunately, for this time the development will continue to focus to MS Marketplace only.
